package gobridge

import (
	"fmt"
	"io"
	"reflect"
	"regexp"
	"sort"
	"strings"
)

func pyType(t Type) string {
	switch t.Kind {
	case "struct":
		return t.Name
	case "ptr":
		return pyType(*t.Elem) + " | None"
	case "slice":
		return "list[" + pyType(*t.Elem) + "] | None"
	case "map":
		return "dict[str, " + pyType(*t.Elem) + "] | None"
	case "string":
		return "str"
	case "bool":
		return "bool"
	case "float32", "float64":
		return "float"
	default:
		return "int"
	}
}

// GeneratePython produces concrete dataclasses, keyword-only method signatures,
// and matching sync/async clients. Regenerate and commit bindings with schema changes.
func (r *Registry) GeneratePython(w io.Writer, class, binary string) error {
	if !regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`).MatchString(class) {
		return fmt.Errorf("class must be a Python class identifier")
	}
	if !regexp.MustCompile(`^[A-Za-z0-9_-]+$`).MatchString(binary) {
		return fmt.Errorf("binary must be a filename stem")
	}
	types := map[string]Type{}
	reserved := map[string]bool{"Client": true, "AsyncClient": true, "decode": true, "dataclass": true, "resolve_binary": true, "str": true, "int": true, "float": true, "bool": true, "dict": true, "list": true, class: true, "Async" + class: true}
	var visit func(Type) error
	visit = func(t Type) error {
		if t.Elem != nil {
			return visit(*t.Elem)
		}
		if t.Kind != "struct" {
			return nil
		}
		if !regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_]*$`).MatchString(t.Name) {
			return fmt.Errorf("type name %s is not a Python identifier", t.Name)
		}
		if reserved[t.Name] || pythonReserved[t.Name] {
			return fmt.Errorf("type name %s conflicts with generated symbols", t.Name)
		}
		if old, ok := types[t.Name]; ok && !reflect.DeepEqual(old, t) {
			return fmt.Errorf("conflicting type name %s", t.Name)
		}
		types[t.Name] = t
		for _, f := range t.Fields {
			if err := visit(f.Type); err != nil {
				return err
			}
		}
		return nil
	}
	s := r.Schema()
	for _, op := range s.Operations {
		if err := visit(op.Input); err != nil {
			return err
		}
		if err := visit(op.Output); err != nil {
			return err
		}
	}
	var b strings.Builder
	fmt.Fprint(&b, "# Generated by gobridge; DO NOT EDIT.\nfrom __future__ import annotations\nfrom dataclasses import dataclass\nfrom gobridge import Client, AsyncClient, decode, resolve_binary\n\n")
	names := make([]string, 0, len(types))
	for n := range types {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		fmt.Fprintf(&b, "@dataclass(frozen=True, kw_only=True)\nclass %s:\n", n)
		if len(types[n].Fields) == 0 {
			fmt.Fprintln(&b, "    pass")
		}
		for _, f := range types[n].Fields {
			def := ""
			if f.Type.Kind == "ptr" {
				def = " = None"
			}
			fmt.Fprintf(&b, "    %s: %s%s\n", f.Name, pyType(f.Type), def)
		}
		fmt.Fprintln(&b)
	}
	for _, async := range []bool{false, true} {
		c, base, prefix, call := class, "Client", "", "self.call"
		if async {
			c = "Async" + class
			base = "AsyncClient"
			prefix = "async "
			call = "await self.acall"
		}
		fmt.Fprintf(&b, "class %s(%s):\n", c, base)
		fmt.Fprintf(&b, "    def __init__(self, command=None, *, timeout: float = 30, max_pending: int = 128):\n        super().__init__(command if command is not None else resolve_binary(__file__, %q), timeout=timeout, max_pending=max_pending, expected_schema=%q)\n\n", binary, s.Hash)
		for _, op := range s.Operations {
			fmt.Fprintf(&b, "    %sdef %s(self, *", prefix, op.Name)
			for _, f := range op.Input.Fields {
				def := ""
				if f.Type.Kind == "ptr" {
					def = " = None"
				}
				fmt.Fprintf(&b, ", %s: %s%s", f.Name, pyType(f.Type), def)
			}
			fmt.Fprintf(&b, ", _timeout: float | None = None) -> %s:\n", op.Output.Name)
			fmt.Fprintf(&b, "        %q\n", op.Description)
			fmt.Fprintf(&b, "        result = %s(%q, {", call, op.Name)
			for j, f := range op.Input.Fields {
				if j > 0 {
					fmt.Fprint(&b, ", ")
				}
				fmt.Fprintf(&b, "%q: %s", f.Name, f.Name)
			}
			fmt.Fprintf(&b, "}, timeout=_timeout)\n        return decode(%s, result)\n\n", op.Output.Name)
		}
	}
	_, err := io.WriteString(w, b.String())
	return err
}
