package gobridge

import (
	"encoding/json"
	"fmt"
	"io"
	"reflect"
	"regexp"
	"sort"
	"strings"
)

func pyType(t Type) string {
	switch t.Kind {
	case "void":
		return "None"
	case "struct":
		return t.Name
	case "ptr":
		return pyType(*t.Elem) + " | None"
	case "slice":
		return "list[" + pyType(*t.Elem) + "] | None"
	case "map":
		return "dict[str, " + pyType(*t.Elem) + "] | None"
	case "string":
		return "str"
	case "bool":
		return "bool"
	case "float32", "float64":
		return "float"
	default:
		return "int"
	}
}

func pyDecodeType(t Type) string {
	switch t.Kind {
	case "struct":
		return "_bridge_type_" + t.Name
	case "ptr":
		return pyDecodeType(*t.Elem) + " | None"
	case "slice":
		return "list[" + pyDecodeType(*t.Elem) + "] | None"
	case "map":
		return "dict[str, " + pyDecodeType(*t.Elem) + "] | None"
	default:
		return pyType(t)
	}
}

func pyFields(b *strings.Builder, fields []Field) {
	for _, f := range fields {
		def := ""
		if f.Type.Kind == "ptr" {
			def = " = None"
		}
		fmt.Fprintf(b, ", %s: %s%s", f.Name, pyType(f.Type), def)
	}
}

func pyParams(b *strings.Builder, fields []Field) {
	fmt.Fprint(b, "{")
	for j, f := range fields {
		if j > 0 {
			fmt.Fprint(b, ", ")
		}
		fmt.Fprintf(b, "%q: %s", f.Name, f.Name)
	}
	fmt.Fprint(b, "}")
}

func pyMethod(b *strings.Builder, op Operation, indent, prefix, receiver, call string) {
	fmt.Fprintf(b, "%s%sdef %s(%s*", indent, prefix, op.Name, receiver)
	pyFields(b, op.Input.Fields)
	fmt.Fprintf(b, ", _timeout: float | None = None) -> %s:\n", pyType(op.Output))
	fmt.Fprintf(b, "%s    %q\n", indent, op.Description)
	fmt.Fprintf(b, "%s    result = %s(%q, ", indent, call, op.Name)
	pyParams(b, op.Input.Fields)
	fmt.Fprintf(b, ", timeout=_timeout)\n%s    return _bridge_decode(%s, result)\n\n", indent, pyDecodeType(op.Output))
}

// GeneratePython emits concrete dataclasses, constructors and keyword-only
// functions/methods, plus lazy module defaults and explicit scope controls.
func (r *Registry) GeneratePython(w io.Writer, class, binary string) error {
	if !regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`).MatchString(class) {
		return fmt.Errorf("class must be a Python class identifier")
	}
	if !regexp.MustCompile(`^[A-Za-z0-9_-]+$`).MatchString(binary) {
		return fmt.Errorf("binary must be a filename stem")
	}
	types := map[string]Type{}
	reserved := map[string]bool{}
	for _, n := range strings.Fields("Client AsyncClient RuntimeOptions DefaultControl decode dataclass resolve_binary control aio str int float bool dict list") {
		reserved[n] = true
	}
	if reserved[class] || pythonReserved[class] {
		return fmt.Errorf("class %s conflicts with generated symbols", class)
	}
	reserved[class], reserved["Async"+class] = true, true
	var visit func(Type) error
	visit = func(t Type) error {
		if t.Elem != nil {
			return visit(*t.Elem)
		}
		if t.Kind != "struct" {
			return nil
		}
		if !regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_]*$`).MatchString(t.Name) {
			return fmt.Errorf("type name %s is not a Python identifier", t.Name)
		}
		if reserved[t.Name] || pythonReserved[t.Name] {
			return fmt.Errorf("type name %s conflicts with generated symbols", t.Name)
		}
		if old, ok := types[t.Name]; ok && !reflect.DeepEqual(old, t) {
			return fmt.Errorf("conflicting type name %s", t.Name)
		}
		types[t.Name] = t
		for _, f := range t.Fields {
			if err := visit(f.Type); err != nil {
				return err
			}
		}
		return nil
	}
	s := r.Schema()
	if s.Constructor != nil {
		if err := visit(*s.Constructor); err != nil {
			return err
		}
	}
	for _, op := range s.Operations {
		if reserved[op.Name] {
			return fmt.Errorf("operation %s conflicts with generated symbols", op.Name)
		}
		if err := visit(op.Input); err != nil {
			return err
		}
		if err := visit(op.Output); err != nil {
			return err
		}
	}
	for _, op := range s.Operations {
		if _, ok := types[op.Name]; ok {
			return fmt.Errorf("operation %s conflicts with generated type", op.Name)
		}
	}
	var b strings.Builder
	fmt.Fprint(&b, "# Generated by gobridge; DO NOT EDIT.\nfrom __future__ import annotations\nfrom dataclasses import dataclass, field as _bridge_field\nfrom gobridge import Client, AsyncClient, RuntimeOptions, DefaultControl, decode as _bridge_decode, resolve_binary as _bridge_resolve_binary\n\n")
	names := make([]string, 0, len(types))
	for n := range types {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		fmt.Fprintf(&b, "@dataclass(frozen=True, kw_only=True)\nclass %s:\n", n)
		if len(types[n].Fields) == 0 {
			fmt.Fprintln(&b, "    pass")
		}
		for _, f := range types[n].Fields {
			def := ""
			if f.Type.Kind == "ptr" {
				def = " = None"
			}
			metadata := map[string]any{}
			if f.Description != "" {
				metadata["description"] = f.Description
			}
			if f.Constraints != nil {
				metadata["constraints"] = f.Constraints
			}
			if len(metadata) != 0 {
				// Strings, dictionaries and finite numbers render as literals
				// accepted by both JSON and Python, preserving exact integers.
				data, err := json.Marshal(metadata)
				if err != nil {
					return err
				}
				def = " = _bridge_field(metadata=" + string(data)
				if f.Type.Kind == "ptr" {
					def += ", default=None"
				}
				def += ")"
			}
			fmt.Fprintf(&b, "    %s: %s%s\n", f.Name, pyType(f.Type), def)
		}
		fmt.Fprintln(&b)
	}
	for _, n := range names {
		fmt.Fprintf(&b, "_bridge_type_%s = %s\n", n, n)
	}
	fmt.Fprintln(&b)
	for _, async := range []bool{false, true} {
		c, base, prefix, call := class, "Client", "", "self.call"
		if async {
			c, base, prefix, call = "Async"+class, "AsyncClient", "async ", "await self.acall"
		}
		fmt.Fprintf(&b, "class %s(%s):\n    def __init__(self, command=None, *", c, base)
		if s.Constructor != nil {
			pyFields(&b, s.Constructor.Fields)
		}
		fmt.Fprint(&b, ", _runtime: RuntimeOptions | None = None):\n        _bridge_options = _runtime or RuntimeOptions()\n")
		fmt.Fprintf(&b, "        command = command if command is not None else _bridge_options.command\n        command = command if command is not None else _bridge_resolve_binary(__file__, %q)\n", binary)
		fmt.Fprint(&b, "        super().__init__(command, timeout=_bridge_options.timeout, max_pending=_bridge_options.max_pending,\n                         startup_timeout=_bridge_options.startup_timeout, ")
		fmt.Fprintf(&b, "expected_schema=%q", s.Hash)
		if s.Constructor != nil {
			fmt.Fprint(&b, ", init=")
			pyParams(&b, s.Constructor.Fields)
		}
		fmt.Fprint(&b, ")\n\n")
		for _, op := range s.Operations {
			pyMethod(&b, op, "    ", prefix, "self, ", call)
		}
	}
	fmt.Fprintf(&b, "control = _bridge_control = DefaultControl(%s)\n\n", class)
	for _, op := range s.Operations {
		pyMethod(&b, op, "", "", "", "_bridge_control.client().call")
	}
	fmt.Fprint(&b, "class _AsyncFunctions:\n")
	if len(s.Operations) == 0 {
		fmt.Fprint(&b, "    pass\n\n")
	}
	for _, op := range s.Operations {
		pyMethod(&b, op, "    ", "async ", "self, ", "await _bridge_control.client().acall")
	}
	fmt.Fprint(&b, "aio = _AsyncFunctions()\n")
	_, err := io.WriteString(w, b.String())
	return err
}
