// Code generated by gobridge generate; DO NOT EDIT.

package main

import _gobridge "github.com/sambhav/gobridge"

// NewGobridge registers annotated operations without running their constructors.
func NewGobridge(_options ..._gobridge.Option) (*_gobridge.Registry, error) {
	_registry := _gobridge.New(append([]_gobridge.Option{_gobridge.WithPython(_gobridge.Names{Operations: map[string]string{"echo": "round_trip"}}), _gobridge.WithTypeScript(_gobridge.Names{Operations: map[string]string{"echo": "roundTrip"}})}, _options...)...)
	if _err := _gobridge.Bind(_registry, "echo", Echo, "value"); _err != nil {
		return nil, _err
	}
	if _err := _gobridge.Bind(_registry, "empty", Empty, "value"); _err != nil {
		return nil, _err
	}
	if _err := _gobridge.Bind(_registry, "show", Show, "value"); _err != nil {
		return nil, _err
	}
	if _err := _gobridge.Bind(_registry, "signed", Signed, "value"); _err != nil {
		return nil, _err
	}
	return _registry, nil
}

func (Level) GobridgeEnum() map[string]Level { return map[string]Level{"Small": Small, "Huge": Huge} }

func (Mode) GobridgeEnum() map[string]Mode { return map[string]Mode{"Fast": Fast, "Careful": Careful} }
