// Code generated by gobridge generate; DO NOT EDIT.

package main

import _gobridge "github.com/sambhav/gobridge"

// NewGobridge registers annotated operations without running their constructors.
func NewGobridge(_options ..._gobridge.Option) (*_gobridge.Registry, error) {
	_registry := _gobridge.New(_options...)
	_object, _err := _gobridge.NewSharedObject(_registry, NewAuthClient)
	if _err != nil {
		return nil, _err
	}
	if _err := _gobridge.Bind(_registry, "constructions", Constructions); _err != nil {
		return nil, _err
	}
	if _err := _object.Bind("identify", (*AuthClient).Identify); _err != nil {
		return nil, _err
	}
	if _err := _gobridge.Bind(_registry, "process_id", ProcessID); _err != nil {
		return nil, _err
	}
	if _err := _object.Bind("watch", (*AuthClient).Watch, "count"); _err != nil {
		return nil, _err
	}
	return _registry, nil
}
