# Generated by gobridge; DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass, field as _bridge_field
from gobridge import Client, AsyncClient, RuntimeOptions, DefaultControl, decode as _bridge_decode, resolve_binary as _bridge_resolve_binary

@dataclass(frozen=True, kw_only=True)
class CachedGreeting:
    message: str
    computation: int
    process_id: int

@dataclass(frozen=True, kw_only=True)
class GreetInput:
    name: str

@dataclass(frozen=True, kw_only=True)
class Greeting:
    message: str

_bridge_type_CachedGreeting = CachedGreeting
_bridge_type_GreetInput = GreetInput
_bridge_type_Greeting = Greeting

class Hello(Client):
    def __init__(self, command=None, *, _runtime: RuntimeOptions | None = None):
        _bridge_options = _runtime or RuntimeOptions()
        command = command if command is not None else _bridge_options.command
        command = command if command is not None else _bridge_resolve_binary(__file__, "hello")
        super().__init__(command, timeout=_bridge_options.timeout, max_pending=_bridge_options.max_pending,
                         startup_timeout=_bridge_options.startup_timeout, expected_schema="288b4d5813bf9cc6561a3d52b67d5089380f61b327f2bfb0df180ac79def362e")

    def cached_greet(self, *, name: str, _timeout: float | None = None) -> CachedGreeting:
        "Greet with a bounded Go cache shared by calls on this client."
        result = self.call("cached_greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(_bridge_type_CachedGreeting, result)

    def greet(self, *, name: str, _timeout: float | None = None) -> Greeting:
        "Greet someone using an ordinary Go function."
        result = self.call("greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Greeting, result)

class AsyncHello(AsyncClient):
    def __init__(self, command=None, *, _runtime: RuntimeOptions | None = None):
        _bridge_options = _runtime or RuntimeOptions()
        command = command if command is not None else _bridge_options.command
        command = command if command is not None else _bridge_resolve_binary(__file__, "hello")
        super().__init__(command, timeout=_bridge_options.timeout, max_pending=_bridge_options.max_pending,
                         startup_timeout=_bridge_options.startup_timeout, expected_schema="288b4d5813bf9cc6561a3d52b67d5089380f61b327f2bfb0df180ac79def362e")

    async def cached_greet(self, *, name: str, _timeout: float | None = None) -> CachedGreeting:
        "Greet with a bounded Go cache shared by calls on this client."
        result = await self.acall("cached_greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(_bridge_type_CachedGreeting, result)

    async def greet(self, *, name: str, _timeout: float | None = None) -> Greeting:
        "Greet someone using an ordinary Go function."
        result = await self.acall("greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Greeting, result)

control = _bridge_control = DefaultControl(Hello)

def cached_greet(*, name: str, _timeout: float | None = None) -> CachedGreeting:
    "Greet with a bounded Go cache shared by calls on this client."
    result = _bridge_control.client().call("cached_greet", {"name": name}, timeout=_timeout)
    return _bridge_decode(_bridge_type_CachedGreeting, result)

def greet(*, name: str, _timeout: float | None = None) -> Greeting:
    "Greet someone using an ordinary Go function."
    result = _bridge_control.client().call("greet", {"name": name}, timeout=_timeout)
    return _bridge_decode(_bridge_type_Greeting, result)

class _AsyncFunctions:
    async def cached_greet(self, *, name: str, _timeout: float | None = None) -> CachedGreeting:
        "Greet with a bounded Go cache shared by calls on this client."
        result = await _bridge_control.client().acall("cached_greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(_bridge_type_CachedGreeting, result)

    async def greet(self, *, name: str, _timeout: float | None = None) -> Greeting:
        "Greet someone using an ordinary Go function."
        result = await _bridge_control.client().acall("greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Greeting, result)

aio = _AsyncFunctions()
