# Generated by gobridge; DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass, field as _bridge_field
from typing import ContextManager as _bridge_ContextManager, AsyncContextManager as _bridge_AsyncContextManager
from gobridge import Client, AsyncClient, RuntimeOptions, decode as _bridge_decode, resolve_binary as _bridge_resolve_binary
from gobridge.defaults import DefaultControl as _bridge_Defaults
from gobridge.runtime import require_sync as _bridge_require_sync

__all__ = ["Hello","SyncHello","configure","session","session_sync","shutdown","shutdown_sync","CachedGreeting","GreetInput","Greeting","cached_greet","cached_greet_sync","greet","greet_sync"]

@dataclass(frozen=True, kw_only=True)
class CachedGreeting:
    message: str
    computation: int
    process_id: int

@dataclass(frozen=True, kw_only=True)
class GreetInput:
    name: str

@dataclass(frozen=True, kw_only=True)
class Greeting:
    message: str

_bridge_type_CachedGreeting = CachedGreeting
_bridge_type_GreetInput = GreetInput
_bridge_type_Greeting = Greeting

class SyncHello(Client):
    def __init__(self, command=None, *, _runtime: RuntimeOptions | None = None):
        _bridge_options = _runtime or RuntimeOptions()
        command = command if command is not None else _bridge_options.command
        command = command if command is not None else _bridge_resolve_binary(__file__, "hello")
        super().__init__(command, timeout=_bridge_options.timeout, max_pending=_bridge_options.max_pending,
                         startup_timeout=_bridge_options.startup_timeout, expected_schema="288b4d5813bf9cc6561a3d52b67d5089380f61b327f2bfb0df180ac79def362e")

    def __enter__(self):
        _bridge_require_sync()
        return super().__enter__()

    def cached_greet(self, *, name: str, _timeout: float | None = None) -> CachedGreeting:
        "Greet with a bounded Go cache shared by calls on this client."
        _bridge_require_sync()
        result = self.call("cached_greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(_bridge_type_CachedGreeting, result)

    def greet(self, *, name: str, _timeout: float | None = None) -> Greeting:
        "Greet someone using an ordinary Go function."
        _bridge_require_sync()
        result = self.call("greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Greeting, result)

class Hello(AsyncClient):
    def __init__(self, command=None, *, _runtime: RuntimeOptions | None = None):
        _bridge_options = _runtime or RuntimeOptions()
        command = command if command is not None else _bridge_options.command
        command = command if command is not None else _bridge_resolve_binary(__file__, "hello")
        super().__init__(command, timeout=_bridge_options.timeout, max_pending=_bridge_options.max_pending,
                         startup_timeout=_bridge_options.startup_timeout, expected_schema="288b4d5813bf9cc6561a3d52b67d5089380f61b327f2bfb0df180ac79def362e")

    def __enter__(self):
        raise TypeError("use async with Hello(...), or with SyncHello(...)")

    async def cached_greet(self, *, name: str, _timeout: float | None = None) -> CachedGreeting:
        "Greet with a bounded Go cache shared by calls on this client."
        result = await self.acall("cached_greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(_bridge_type_CachedGreeting, result)

    async def greet(self, *, name: str, _timeout: float | None = None) -> Greeting:
        "Greet someone using an ordinary Go function."
        result = await self.acall("greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Greeting, result)

_bridge_defaults = _bridge_Defaults(SyncHello)

async def cached_greet(*, name: str, _timeout: float | None = None) -> CachedGreeting:
    "Greet with a bounded Go cache shared by calls on this client."
    result = await _bridge_defaults.client().acall("cached_greet", {"name": name}, timeout=_timeout)
    return _bridge_decode(_bridge_type_CachedGreeting, result)

def cached_greet_sync(*, name: str, _timeout: float | None = None) -> CachedGreeting:
    "Greet with a bounded Go cache shared by calls on this client."
    _bridge_require_sync()
    result = _bridge_defaults.client().call("cached_greet", {"name": name}, timeout=_timeout)
    return _bridge_decode(_bridge_type_CachedGreeting, result)

async def greet(*, name: str, _timeout: float | None = None) -> Greeting:
    "Greet someone using an ordinary Go function."
    result = await _bridge_defaults.client().acall("greet", {"name": name}, timeout=_timeout)
    return _bridge_decode(_bridge_type_Greeting, result)

def greet_sync(*, name: str, _timeout: float | None = None) -> Greeting:
    "Greet someone using an ordinary Go function."
    _bridge_require_sync()
    result = _bridge_defaults.client().call("greet", {"name": name}, timeout=_timeout)
    return _bridge_decode(_bridge_type_Greeting, result)

def configure(command=None, *, _runtime: RuntimeOptions | None = None) -> None:
    _bridge_kwargs = {"command": command, "_runtime": _runtime}
    _bridge_defaults.configure(**_bridge_kwargs)

def session(command=None, *, _runtime: RuntimeOptions | None = None) -> _bridge_AsyncContextManager[Hello]:
    _bridge_kwargs = {"command": command, "_runtime": _runtime}
    return _bridge_defaults.scope_for(Hello, _bridge_kwargs)

def session_sync(command=None, *, _runtime: RuntimeOptions | None = None) -> _bridge_ContextManager[SyncHello]:
    _bridge_kwargs = {"command": command, "_runtime": _runtime}
    _bridge_require_sync()
    return _bridge_defaults.scope_for(SyncHello, _bridge_kwargs, asynchronous=False)

async def shutdown() -> None:
    """Close/reset the module default; explicit sessions stay open."""
    await _bridge_defaults.aclose()

def shutdown_sync() -> None:
    """Close/reset the default from synchronous code."""
    _bridge_require_sync()
    _bridge_defaults.close()
