// Generated by gobridge; DO NOT EDIT.
import { Client as _bridgeClient, DefaultControl as _bridgeDefaultControl, resolveBinary as _bridgeResolveBinary, parseSchema as _bridgeParseSchema, encode as _bridgeEncode, decode as _bridgeDecode } from "gobridge-runtime";
import type { CallOptions as _bridgeCallOptions, RuntimeOptions as _bridgeRuntimeOptions, Schema as _bridgeSchema } from "gobridge-runtime";

/** Shared schema, parsed from JSON text to preserve exact int64 constraint literals. */
export const schema: _bridgeSchema = _bridgeParseSchema("{\"protocol\":1,\"schema_hash\":\"288b4d5813bf9cc6561a3d52b67d5089380f61b327f2bfb0df180ac79def362e\",\"operations\":[{\"name\":\"cached_greet\",\"description\":\"Greet with a bounded Go cache shared by calls on this client.\",\"input\":{\"kind\":\"struct\",\"name\":\"GreetInput\",\"fields\":[{\"name\":\"name\",\"type\":{\"kind\":\"string\"}}]},\"output\":{\"kind\":\"struct\",\"name\":\"CachedGreeting\",\"fields\":[{\"name\":\"message\",\"type\":{\"kind\":\"string\"}},{\"name\":\"computation\",\"type\":{\"kind\":\"int64\"}},{\"name\":\"process_id\",\"type\":{\"kind\":\"int\"}}]}},{\"name\":\"greet\",\"description\":\"Greet someone using an ordinary Go function.\",\"input\":{\"kind\":\"struct\",\"name\":\"GreetInput\",\"fields\":[{\"name\":\"name\",\"type\":{\"kind\":\"string\"}}]},\"output\":{\"kind\":\"struct\",\"name\":\"Greeting\",\"fields\":[{\"name\":\"message\",\"type\":{\"kind\":\"string\"}}]}}]}");

export interface CachedGreeting {
  readonly message: string;
  readonly computation: bigint;
  readonly processId: number;
}

export interface GreetInput {
  readonly name: string;
}

export interface Greeting {
  readonly message: string;
}

export interface HelloOptions {
  /** Optional transport settings; ordinary use resolves the bundled executable. */
  readonly _runtime?: _bridgeRuntimeOptions;
}

const _bridgeOp0 = schema.operations[0]!;
const _bridgeOp1 = schema.operations[1]!;

export class Hello extends _bridgeClient {
  constructor(options: HelloOptions = {}) {
    const { _runtime, ..._bridgeConfig } = options;
    const _bridgeOptions = _runtime ?? {};
    _bridgeEncode({ kind: "struct", name: "HelloOptions", fields: [] }, _bridgeConfig);
    super(_bridgeOptions.command ?? _bridgeResolveBinary(import.meta.url, "hello"), {
      ..._bridgeOptions,
      expectedSchema: schema.schema_hash,
    });
  }

  /**
   * Greet with a bounded Go cache shared by calls on this client.
   */
  async cachedGreet(params: GreetInput, options?: _bridgeCallOptions): Promise<CachedGreeting> {
    const _bridgeResult = await super.call("cached_greet", _bridgeEncode(_bridgeOp0.input, params), options);
    return _bridgeDecode<CachedGreeting>(_bridgeOp0.output, _bridgeResult);
  }

  /**
   * Greet someone using an ordinary Go function.
   */
  async greet(params: GreetInput, options?: _bridgeCallOptions): Promise<Greeting> {
    const _bridgeResult = await super.call("greet", _bridgeEncode(_bridgeOp1.input, params), options);
    return _bridgeDecode<Greeting>(_bridgeOp1.output, _bridgeResult);
  }

}

export const control = new _bridgeDefaultControl<HelloOptions, Hello>((options) => new Hello(options));

/**
 * Greet with a bounded Go cache shared by calls on this client.
 */
export function cachedGreet(params: GreetInput, options?: _bridgeCallOptions): Promise<CachedGreeting> {
  return control.client().cachedGreet(params, options);
}

/**
 * Greet someone using an ordinary Go function.
 */
export function greet(params: GreetInput, options?: _bridgeCallOptions): Promise<Greeting> {
  return control.client().greet(params, options);
}

