// Generated by gobridge; DO NOT EDIT.
import { Client as _bridgeClient, DefaultControl as _bridgeDefaultControl, resolveBinary as _bridgeResolveBinary, parseSchema as _bridgeParseSchema, encode as _bridgeEncode, decode as _bridgeDecode } from "gobridge-runtime";
import type { CallOptions as _bridgeCallOptions, RuntimeOptions as _bridgeRuntimeOptions, Schema as _bridgeSchema } from "gobridge-runtime";

/** Shared schema, parsed from JSON text to preserve exact int64 constraint literals. */
export const schema: _bridgeSchema = _bridgeParseSchema("{\"protocol\":1,\"schema_hash\":\"c6058a2c0f513c328f57e373ed031ec40d724d76e021e56aeaf83f9cbeec98a8\",\"operations\":[{\"name\":\"greet\",\"description\":\"Greet returns a friendly greeting using an ordinary Go function.\",\"input\":{\"kind\":\"struct\",\"name\":\"GreetParams\",\"fields\":[{\"name\":\"name\",\"type\":{\"kind\":\"string\"}}]},\"output\":{\"kind\":\"string\"}},{\"name\":\"reset\",\"description\":\"Reset clears the instance's call counter and returns None in Python.\",\"input\":{\"kind\":\"struct\",\"name\":\"ResetParams\"},\"output\":{\"kind\":\"void\"}},{\"name\":\"stats\",\"description\":\"Statistics reports calls owned by this instance.\",\"input\":{\"kind\":\"struct\",\"name\":\"StatsParams\"},\"output\":{\"kind\":\"struct\",\"name\":\"Stats\",\"fields\":[{\"name\":\"calls\",\"type\":{\"kind\":\"int64\"}},{\"name\":\"process_id\",\"type\":{\"kind\":\"int\"}}]}},{\"name\":\"welcome\",\"description\":\"Welcome greets someone with this client's configured prefix.\",\"input\":{\"kind\":\"struct\",\"name\":\"WelcomeParams\",\"fields\":[{\"name\":\"name\",\"type\":{\"kind\":\"string\"}}]},\"output\":{\"kind\":\"string\"}}],\"constructor\":{\"kind\":\"struct\",\"name\":\"Options\",\"fields\":[{\"name\":\"prefix\",\"type\":{\"kind\":\"ptr\",\"elem\":{\"kind\":\"string\"}}}]}}");

export interface GreetParams {
  readonly name: string;
}

export interface Options {
  readonly prefix?: string | null;
}

export interface ResetParams {
}

export interface Stats {
  readonly calls: bigint;
  readonly processId: number;
}

export interface StatsParams {
}

export interface WelcomeParams {
  readonly name: string;
}

export interface GreeterOptions {
  readonly prefix?: string | null;
  /** Optional transport settings; ordinary use resolves the bundled executable. */
  readonly _runtime?: _bridgeRuntimeOptions;
}

const _bridgeOp0 = schema.operations[0]!;
const _bridgeOp1 = schema.operations[1]!;
const _bridgeOp2 = schema.operations[2]!;
const _bridgeOp3 = schema.operations[3]!;

export class Greeter extends _bridgeClient {
  constructor(options: GreeterOptions = {}) {
    const { _runtime, ..._bridgeConfig } = options;
    const _bridgeOptions = _runtime ?? {};
    super(_bridgeOptions.command ?? _bridgeResolveBinary(import.meta.url, "greeter"), {
      ..._bridgeOptions,
      expectedSchema: schema.schema_hash,
      init: _bridgeEncode(schema.constructor!, _bridgeConfig),
    });
  }

  /**
   * Greet returns a friendly greeting using an ordinary Go function.
   */
  async greet(params: GreetParams, options?: _bridgeCallOptions): Promise<string> {
    const _bridgeResult = await super.call("greet", _bridgeEncode(_bridgeOp0.input, params), options);
    return _bridgeDecode<string>(_bridgeOp0.output, _bridgeResult);
  }

  /**
   * Reset clears the instance's call counter and returns None in Python.
   */
  async reset(options?: _bridgeCallOptions): Promise<void> {
    const _bridgeResult = await super.call("reset", _bridgeEncode(_bridgeOp1.input, {}), options);
    return _bridgeDecode<void>(_bridgeOp1.output, _bridgeResult);
  }

  /**
   * Statistics reports calls owned by this instance.
   */
  async stats(options?: _bridgeCallOptions): Promise<Stats> {
    const _bridgeResult = await super.call("stats", _bridgeEncode(_bridgeOp2.input, {}), options);
    return _bridgeDecode<Stats>(_bridgeOp2.output, _bridgeResult);
  }

  /**
   * Welcome greets someone with this client's configured prefix.
   */
  async welcome(params: WelcomeParams, options?: _bridgeCallOptions): Promise<string> {
    const _bridgeResult = await super.call("welcome", _bridgeEncode(_bridgeOp3.input, params), options);
    return _bridgeDecode<string>(_bridgeOp3.output, _bridgeResult);
  }

}

const _bridgeDefaults = new _bridgeDefaultControl<GreeterOptions, Greeter>((options) => new Greeter(options));

export function configure(options: GreeterOptions): void {
  _bridgeDefaults.configure(options);
}

export function session<R>(options: GreeterOptions, callback: (client: Greeter) => R | Promise<R>): Promise<R> {
  return _bridgeDefaults.scope(options, callback);
}

export function shutdown(): Promise<void> {
  return _bridgeDefaults.close();
}

/**
 * Greet returns a friendly greeting using an ordinary Go function.
 */
export function greet(params: GreetParams, options?: _bridgeCallOptions): Promise<string> {
  return _bridgeDefaults.client().greet(params, options);
}

/**
 * Reset clears the instance's call counter and returns None in Python.
 */
export function reset(options?: _bridgeCallOptions): Promise<void> {
  return _bridgeDefaults.client().reset(options);
}

/**
 * Statistics reports calls owned by this instance.
 */
export function stats(options?: _bridgeCallOptions): Promise<Stats> {
  return _bridgeDefaults.client().stats(options);
}

/**
 * Welcome greets someone with this client's configured prefix.
 */
export function welcome(params: WelcomeParams, options?: _bridgeCallOptions): Promise<string> {
  return _bridgeDefaults.client().welcome(params, options);
}

