# Generated by gobridge; DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass, field as _bridge_field
from typing import ContextManager as _bridge_ContextManager, AsyncContextManager as _bridge_AsyncContextManager
from gobridge import Client, AsyncClient, RuntimeOptions, decode as _bridge_decode, resolve_binary as _bridge_resolve_binary
from gobridge.defaults import DefaultControl as _bridge_Defaults
from gobridge.runtime import require_sync as _bridge_require_sync

__all__ = ["Greeter","SyncGreeter","configure","session","session_sync","shutdown","shutdown_sync","GreetParams","Options","ResetParams","Stats","StatsParams","WelcomeParams","greet","greet_sync","reset","reset_sync","stats","stats_sync","welcome","welcome_sync"]

@dataclass(frozen=True, kw_only=True)
class GreetParams:
    name: str

@dataclass(frozen=True, kw_only=True)
class Options:
    prefix: str | None = None

@dataclass(frozen=True, kw_only=True)
class ResetParams:
    pass

@dataclass(frozen=True, kw_only=True)
class Stats:
    calls: int
    process_id: int

@dataclass(frozen=True, kw_only=True)
class StatsParams:
    pass

@dataclass(frozen=True, kw_only=True)
class WelcomeParams:
    name: str

_bridge_type_GreetParams = GreetParams
_bridge_type_Options = Options
_bridge_type_ResetParams = ResetParams
_bridge_type_Stats = Stats
_bridge_type_StatsParams = StatsParams
_bridge_type_WelcomeParams = WelcomeParams

class SyncGreeter(Client):
    def __init__(self, command=None, *, prefix: str | None = None, _runtime: RuntimeOptions | None = None):
        _bridge_options = _runtime or RuntimeOptions()
        command = command if command is not None else _bridge_options.command
        command = command if command is not None else _bridge_resolve_binary(__file__, "greeter")
        super().__init__(command, timeout=_bridge_options.timeout, max_pending=_bridge_options.max_pending,
                         startup_timeout=_bridge_options.startup_timeout, expected_schema="c6058a2c0f513c328f57e373ed031ec40d724d76e021e56aeaf83f9cbeec98a8", init={"prefix": prefix})

    def __enter__(self):
        _bridge_require_sync()
        return super().__enter__()

    def greet(self, *, name: str, _timeout: float | None = None) -> str:
        "Greet returns a friendly greeting using an ordinary Go function."
        _bridge_require_sync()
        result = self.call("greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(str, result)

    def reset(self, *, _timeout: float | None = None) -> None:
        "Reset clears the instance's call counter and returns None in Python."
        _bridge_require_sync()
        result = self.call("reset", {}, timeout=_timeout)
        return _bridge_decode(None, result)

    def stats(self, *, _timeout: float | None = None) -> Stats:
        "Statistics reports calls owned by this instance."
        _bridge_require_sync()
        result = self.call("stats", {}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Stats, result)

    def welcome(self, *, name: str, _timeout: float | None = None) -> str:
        "Welcome greets someone with this client's configured prefix."
        _bridge_require_sync()
        result = self.call("welcome", {"name": name}, timeout=_timeout)
        return _bridge_decode(str, result)

class Greeter(AsyncClient):
    def __init__(self, command=None, *, prefix: str | None = None, _runtime: RuntimeOptions | None = None):
        _bridge_options = _runtime or RuntimeOptions()
        command = command if command is not None else _bridge_options.command
        command = command if command is not None else _bridge_resolve_binary(__file__, "greeter")
        super().__init__(command, timeout=_bridge_options.timeout, max_pending=_bridge_options.max_pending,
                         startup_timeout=_bridge_options.startup_timeout, expected_schema="c6058a2c0f513c328f57e373ed031ec40d724d76e021e56aeaf83f9cbeec98a8", init={"prefix": prefix})

    def __enter__(self):
        raise TypeError("use async with Greeter(...), or with SyncGreeter(...)")

    async def greet(self, *, name: str, _timeout: float | None = None) -> str:
        "Greet returns a friendly greeting using an ordinary Go function."
        result = await self.acall("greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(str, result)

    async def reset(self, *, _timeout: float | None = None) -> None:
        "Reset clears the instance's call counter and returns None in Python."
        result = await self.acall("reset", {}, timeout=_timeout)
        return _bridge_decode(None, result)

    async def stats(self, *, _timeout: float | None = None) -> Stats:
        "Statistics reports calls owned by this instance."
        result = await self.acall("stats", {}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Stats, result)

    async def welcome(self, *, name: str, _timeout: float | None = None) -> str:
        "Welcome greets someone with this client's configured prefix."
        result = await self.acall("welcome", {"name": name}, timeout=_timeout)
        return _bridge_decode(str, result)

_bridge_defaults = _bridge_Defaults(SyncGreeter)

async def greet(*, name: str, _timeout: float | None = None) -> str:
    "Greet returns a friendly greeting using an ordinary Go function."
    result = await _bridge_defaults.client().acall("greet", {"name": name}, timeout=_timeout)
    return _bridge_decode(str, result)

def greet_sync(*, name: str, _timeout: float | None = None) -> str:
    "Greet returns a friendly greeting using an ordinary Go function."
    _bridge_require_sync()
    result = _bridge_defaults.client().call("greet", {"name": name}, timeout=_timeout)
    return _bridge_decode(str, result)

async def reset(*, _timeout: float | None = None) -> None:
    "Reset clears the instance's call counter and returns None in Python."
    result = await _bridge_defaults.client().acall("reset", {}, timeout=_timeout)
    return _bridge_decode(None, result)

def reset_sync(*, _timeout: float | None = None) -> None:
    "Reset clears the instance's call counter and returns None in Python."
    _bridge_require_sync()
    result = _bridge_defaults.client().call("reset", {}, timeout=_timeout)
    return _bridge_decode(None, result)

async def stats(*, _timeout: float | None = None) -> Stats:
    "Statistics reports calls owned by this instance."
    result = await _bridge_defaults.client().acall("stats", {}, timeout=_timeout)
    return _bridge_decode(_bridge_type_Stats, result)

def stats_sync(*, _timeout: float | None = None) -> Stats:
    "Statistics reports calls owned by this instance."
    _bridge_require_sync()
    result = _bridge_defaults.client().call("stats", {}, timeout=_timeout)
    return _bridge_decode(_bridge_type_Stats, result)

async def welcome(*, name: str, _timeout: float | None = None) -> str:
    "Welcome greets someone with this client's configured prefix."
    result = await _bridge_defaults.client().acall("welcome", {"name": name}, timeout=_timeout)
    return _bridge_decode(str, result)

def welcome_sync(*, name: str, _timeout: float | None = None) -> str:
    "Welcome greets someone with this client's configured prefix."
    _bridge_require_sync()
    result = _bridge_defaults.client().call("welcome", {"name": name}, timeout=_timeout)
    return _bridge_decode(str, result)

def configure(command=None, *, prefix: str | None = None, _runtime: RuntimeOptions | None = None) -> None:
    _bridge_kwargs = {"command": command, "_runtime": _runtime, "prefix": prefix}
    _bridge_defaults.configure(**_bridge_kwargs)

def session(command=None, *, prefix: str | None = None, _runtime: RuntimeOptions | None = None) -> _bridge_AsyncContextManager[Greeter]:
    _bridge_kwargs = {"command": command, "_runtime": _runtime, "prefix": prefix}
    return _bridge_defaults.scope_for(Greeter, _bridge_kwargs)

def session_sync(command=None, *, prefix: str | None = None, _runtime: RuntimeOptions | None = None) -> _bridge_ContextManager[SyncGreeter]:
    _bridge_kwargs = {"command": command, "_runtime": _runtime, "prefix": prefix}
    _bridge_require_sync()
    return _bridge_defaults.scope_for(SyncGreeter, _bridge_kwargs, asynchronous=False)

async def shutdown() -> None:
    """Close/reset the module default; explicit sessions stay open."""
    await _bridge_defaults.aclose()

def shutdown_sync() -> None:
    """Close/reset the default from synchronous code."""
    _bridge_require_sync()
    _bridge_defaults.close()
