# Generated by gobridge; DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass, field as _bridge_field
from gobridge import Client, AsyncClient, RuntimeOptions, DefaultControl, decode as _bridge_decode, resolve_binary as _bridge_resolve_binary

@dataclass(frozen=True, kw_only=True)
class Analysis:
    words: int
    characters: int
    computation: int
    process_id: int

@dataclass(frozen=True, kw_only=True)
class AnalyzeInput:
    text: str

@dataclass(frozen=True, kw_only=True)
class Empty:
    pass

@dataclass(frozen=True, kw_only=True)
class Health:
    process_id: int
    active: int

@dataclass(frozen=True, kw_only=True)
class WaitInput:
    milliseconds: int

@dataclass(frozen=True, kw_only=True)
class WaitResult:
    process_id: int

_bridge_type_Analysis = Analysis
_bridge_type_AnalyzeInput = AnalyzeInput
_bridge_type_Empty = Empty
_bridge_type_Health = Health
_bridge_type_WaitInput = WaitInput
_bridge_type_WaitResult = WaitResult

class TextKit(Client):
    def __init__(self, command=None, *, _runtime: RuntimeOptions | None = None):
        _bridge_options = _runtime or RuntimeOptions()
        command = command if command is not None else _bridge_options.command
        command = command if command is not None else _bridge_resolve_binary(__file__, "textkit")
        super().__init__(command, timeout=_bridge_options.timeout, max_pending=_bridge_options.max_pending,
                         startup_timeout=_bridge_options.startup_timeout, expected_schema="29b9c0dde82e391eaaf292e53d79f08996d07dea980b925695274369cf724472")

    def analyze(self, *, text: str, _timeout: float | None = None) -> Analysis:
        "Count words and Unicode code points; cache results in Go."
        result = self.call("analyze", {"text": text}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Analysis, result)

    def health(self, *, _timeout: float | None = None) -> Health:
        "Inspect the daemon for the integration example."
        result = self.call("health", {}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Health, result)

    def wait(self, *, milliseconds: int, _timeout: float | None = None) -> WaitResult:
        "Wait with cooperative cancellation."
        result = self.call("wait", {"milliseconds": milliseconds}, timeout=_timeout)
        return _bridge_decode(_bridge_type_WaitResult, result)

class AsyncTextKit(AsyncClient):
    def __init__(self, command=None, *, _runtime: RuntimeOptions | None = None):
        _bridge_options = _runtime or RuntimeOptions()
        command = command if command is not None else _bridge_options.command
        command = command if command is not None else _bridge_resolve_binary(__file__, "textkit")
        super().__init__(command, timeout=_bridge_options.timeout, max_pending=_bridge_options.max_pending,
                         startup_timeout=_bridge_options.startup_timeout, expected_schema="29b9c0dde82e391eaaf292e53d79f08996d07dea980b925695274369cf724472")

    async def analyze(self, *, text: str, _timeout: float | None = None) -> Analysis:
        "Count words and Unicode code points; cache results in Go."
        result = await self.acall("analyze", {"text": text}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Analysis, result)

    async def health(self, *, _timeout: float | None = None) -> Health:
        "Inspect the daemon for the integration example."
        result = await self.acall("health", {}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Health, result)

    async def wait(self, *, milliseconds: int, _timeout: float | None = None) -> WaitResult:
        "Wait with cooperative cancellation."
        result = await self.acall("wait", {"milliseconds": milliseconds}, timeout=_timeout)
        return _bridge_decode(_bridge_type_WaitResult, result)

control = _bridge_control = DefaultControl(TextKit)

def analyze(*, text: str, _timeout: float | None = None) -> Analysis:
    "Count words and Unicode code points; cache results in Go."
    result = _bridge_control.client().call("analyze", {"text": text}, timeout=_timeout)
    return _bridge_decode(_bridge_type_Analysis, result)

def health(*, _timeout: float | None = None) -> Health:
    "Inspect the daemon for the integration example."
    result = _bridge_control.client().call("health", {}, timeout=_timeout)
    return _bridge_decode(_bridge_type_Health, result)

def wait(*, milliseconds: int, _timeout: float | None = None) -> WaitResult:
    "Wait with cooperative cancellation."
    result = _bridge_control.client().call("wait", {"milliseconds": milliseconds}, timeout=_timeout)
    return _bridge_decode(_bridge_type_WaitResult, result)

class _AsyncFunctions:
    async def analyze(self, *, text: str, _timeout: float | None = None) -> Analysis:
        "Count words and Unicode code points; cache results in Go."
        result = await _bridge_control.client().acall("analyze", {"text": text}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Analysis, result)

    async def health(self, *, _timeout: float | None = None) -> Health:
        "Inspect the daemon for the integration example."
        result = await _bridge_control.client().acall("health", {}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Health, result)

    async def wait(self, *, milliseconds: int, _timeout: float | None = None) -> WaitResult:
        "Wait with cooperative cancellation."
        result = await _bridge_control.client().acall("wait", {"milliseconds": milliseconds}, timeout=_timeout)
        return _bridge_decode(_bridge_type_WaitResult, result)

aio = _AsyncFunctions()
