# Generated by gobridge; DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from gobridge import Client, AsyncClient, decode, resolve_binary

@dataclass(frozen=True, kw_only=True)
class Analysis:
    words: int
    characters: int
    computation: int
    process_id: int

@dataclass(frozen=True, kw_only=True)
class AnalyzeInput:
    text: str

@dataclass(frozen=True, kw_only=True)
class Empty:
    pass

@dataclass(frozen=True, kw_only=True)
class Health:
    process_id: int
    active: int

@dataclass(frozen=True, kw_only=True)
class WaitInput:
    milliseconds: int

@dataclass(frozen=True, kw_only=True)
class WaitResult:
    process_id: int

class TextKit(Client):
    def __init__(self, command=None, *, timeout: float = 30, max_pending: int = 128):
        super().__init__(command if command is not None else resolve_binary(__file__, "textkit"), timeout=timeout, max_pending=max_pending, expected_schema="29b9c0dde82e391eaaf292e53d79f08996d07dea980b925695274369cf724472")

    def analyze(self, *, text: str, _timeout: float | None = None) -> Analysis:
        "Count words and Unicode code points; cache results in Go."
        result = self.call("analyze", {"text": text}, timeout=_timeout)
        return decode(Analysis, result)

    def health(self, *, _timeout: float | None = None) -> Health:
        "Inspect the daemon for the integration example."
        result = self.call("health", {}, timeout=_timeout)
        return decode(Health, result)

    def wait(self, *, milliseconds: int, _timeout: float | None = None) -> WaitResult:
        "Wait with cooperative cancellation."
        result = self.call("wait", {"milliseconds": milliseconds}, timeout=_timeout)
        return decode(WaitResult, result)

class AsyncTextKit(AsyncClient):
    def __init__(self, command=None, *, timeout: float = 30, max_pending: int = 128):
        super().__init__(command if command is not None else resolve_binary(__file__, "textkit"), timeout=timeout, max_pending=max_pending, expected_schema="29b9c0dde82e391eaaf292e53d79f08996d07dea980b925695274369cf724472")

    async def analyze(self, *, text: str, _timeout: float | None = None) -> Analysis:
        "Count words and Unicode code points; cache results in Go."
        result = await self.acall("analyze", {"text": text}, timeout=_timeout)
        return decode(Analysis, result)

    async def health(self, *, _timeout: float | None = None) -> Health:
        "Inspect the daemon for the integration example."
        result = await self.acall("health", {}, timeout=_timeout)
        return decode(Health, result)

    async def wait(self, *, milliseconds: int, _timeout: float | None = None) -> WaitResult:
        "Wait with cooperative cancellation."
        result = await self.acall("wait", {"milliseconds": milliseconds}, timeout=_timeout)
        return decode(WaitResult, result)

