// Generated by gobridge; DO NOT EDIT.
import { Client as _bridgeClient, DefaultControl as _bridgeDefaultControl, resolveBinary as _bridgeResolveBinary, parseSchema as _bridgeParseSchema, encode as _bridgeEncode, decode as _bridgeDecode } from "gobridge-runtime";
import type { CallOptions as _bridgeCallOptions, RuntimeOptions as _bridgeRuntimeOptions, Schema as _bridgeSchema } from "gobridge-runtime";

/** Shared schema, parsed from JSON text to preserve exact int64 constraint literals. */
export const schema: _bridgeSchema = _bridgeParseSchema("{\"protocol\":1,\"schema_hash\":\"29b9c0dde82e391eaaf292e53d79f08996d07dea980b925695274369cf724472\",\"operations\":[{\"name\":\"analyze\",\"description\":\"Count words and Unicode code points; cache results in Go.\",\"input\":{\"kind\":\"struct\",\"name\":\"AnalyzeInput\",\"fields\":[{\"name\":\"text\",\"type\":{\"kind\":\"string\"}}]},\"output\":{\"kind\":\"struct\",\"name\":\"Analysis\",\"fields\":[{\"name\":\"words\",\"type\":{\"kind\":\"int\"}},{\"name\":\"characters\",\"type\":{\"kind\":\"int\"}},{\"name\":\"computation\",\"type\":{\"kind\":\"int64\"}},{\"name\":\"process_id\",\"type\":{\"kind\":\"int\"}}]}},{\"name\":\"health\",\"description\":\"Inspect the daemon for the integration example.\",\"input\":{\"kind\":\"struct\",\"name\":\"Empty\"},\"output\":{\"kind\":\"struct\",\"name\":\"Health\",\"fields\":[{\"name\":\"process_id\",\"type\":{\"kind\":\"int\"}},{\"name\":\"active\",\"type\":{\"kind\":\"int64\"}}]}},{\"name\":\"wait\",\"description\":\"Wait with cooperative cancellation.\",\"input\":{\"kind\":\"struct\",\"name\":\"WaitInput\",\"fields\":[{\"name\":\"milliseconds\",\"type\":{\"kind\":\"int\"}}]},\"output\":{\"kind\":\"struct\",\"name\":\"WaitResult\",\"fields\":[{\"name\":\"process_id\",\"type\":{\"kind\":\"int\"}}]}}]}");

export interface Analysis {
  readonly words: number;
  readonly characters: number;
  readonly computation: bigint;
  readonly processId: number;
}

export interface AnalyzeInput {
  readonly text: string;
}

export interface Empty {
}

export interface Health {
  readonly processId: number;
  readonly active: bigint;
}

export interface WaitInput {
  readonly milliseconds: number;
}

export interface WaitResult {
  readonly processId: number;
}

export interface TextKitOptions {
  /** Optional transport settings; ordinary use resolves the bundled executable. */
  readonly _runtime?: _bridgeRuntimeOptions;
}

const _bridgeOp0 = schema.operations[0]!;
const _bridgeOp1 = schema.operations[1]!;
const _bridgeOp2 = schema.operations[2]!;

export class TextKit extends _bridgeClient {
  constructor(options: TextKitOptions = {}) {
    const { _runtime, ..._bridgeConfig } = options;
    const _bridgeOptions = _runtime ?? {};
    _bridgeEncode({ kind: "struct", name: "TextKitOptions", fields: [] }, _bridgeConfig);
    super(_bridgeOptions.command ?? _bridgeResolveBinary(import.meta.url, "textkit"), {
      ..._bridgeOptions,
      expectedSchema: schema.schema_hash,
    });
  }

  /**
   * Count words and Unicode code points; cache results in Go.
   */
  async analyze(params: AnalyzeInput, options?: _bridgeCallOptions): Promise<Analysis> {
    const _bridgeResult = await super.call("analyze", _bridgeEncode(_bridgeOp0.input, params), options);
    return _bridgeDecode<Analysis>(_bridgeOp0.output, _bridgeResult);
  }

  /**
   * Inspect the daemon for the integration example.
   */
  async health(options?: _bridgeCallOptions): Promise<Health> {
    const _bridgeResult = await super.call("health", _bridgeEncode(_bridgeOp1.input, {}), options);
    return _bridgeDecode<Health>(_bridgeOp1.output, _bridgeResult);
  }

  /**
   * Wait with cooperative cancellation.
   */
  async wait(params: WaitInput, options?: _bridgeCallOptions): Promise<WaitResult> {
    const _bridgeResult = await super.call("wait", _bridgeEncode(_bridgeOp2.input, params), options);
    return _bridgeDecode<WaitResult>(_bridgeOp2.output, _bridgeResult);
  }

}

export const control = new _bridgeDefaultControl<TextKitOptions, TextKit>((options) => new TextKit(options));

/**
 * Count words and Unicode code points; cache results in Go.
 */
export function analyze(params: AnalyzeInput, options?: _bridgeCallOptions): Promise<Analysis> {
  return control.client().analyze(params, options);
}

/**
 * Inspect the daemon for the integration example.
 */
export function health(options?: _bridgeCallOptions): Promise<Health> {
  return control.client().health(options);
}

/**
 * Wait with cooperative cancellation.
 */
export function wait(params: WaitInput, options?: _bridgeCallOptions): Promise<WaitResult> {
  return control.client().wait(params, options);
}

