# Generated by gobridge; DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass, field as _bridge_field
from typing import ContextManager as _bridge_ContextManager, AsyncContextManager as _bridge_AsyncContextManager
from gobridge import Client, AsyncClient, RuntimeOptions, decode as _bridge_decode, resolve_binary as _bridge_resolve_binary
from gobridge.defaults import DefaultControl as _bridge_Defaults
from gobridge.runtime import require_sync as _bridge_require_sync

__all__ = ["TextKit","SyncTextKit","configure","session","session_sync","shutdown","shutdown_sync","Analysis","AnalyzeInput","Empty","Health","WaitInput","WaitResult","analyze","analyze_sync","health","health_sync","wait","wait_sync"]

@dataclass(frozen=True, kw_only=True)
class Analysis:
    words: int
    characters: int
    computation: int
    process_id: int

@dataclass(frozen=True, kw_only=True)
class AnalyzeInput:
    text: str

@dataclass(frozen=True, kw_only=True)
class Empty:
    pass

@dataclass(frozen=True, kw_only=True)
class Health:
    process_id: int
    active: int

@dataclass(frozen=True, kw_only=True)
class WaitInput:
    milliseconds: int

@dataclass(frozen=True, kw_only=True)
class WaitResult:
    process_id: int

_bridge_type_Analysis = Analysis
_bridge_type_AnalyzeInput = AnalyzeInput
_bridge_type_Empty = Empty
_bridge_type_Health = Health
_bridge_type_WaitInput = WaitInput
_bridge_type_WaitResult = WaitResult

class SyncTextKit(Client):
    def __init__(self, command=None, *, _runtime: RuntimeOptions | None = None):
        _bridge_options = _runtime or RuntimeOptions()
        command = command if command is not None else _bridge_options.command
        command = command if command is not None else _bridge_resolve_binary(__file__, "textkit")
        super().__init__(command, timeout=_bridge_options.timeout, max_pending=_bridge_options.max_pending,
                         startup_timeout=_bridge_options.startup_timeout, expected_schema="29b9c0dde82e391eaaf292e53d79f08996d07dea980b925695274369cf724472")

    def __enter__(self):
        _bridge_require_sync()
        return super().__enter__()

    def analyze(self, *, text: str, _timeout: float | None = None) -> Analysis:
        "Count words and Unicode code points; cache results in Go."
        _bridge_require_sync()
        result = self.call("analyze", {"text": text}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Analysis, result)

    def health(self, *, _timeout: float | None = None) -> Health:
        "Inspect the daemon for the integration example."
        _bridge_require_sync()
        result = self.call("health", {}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Health, result)

    def wait(self, *, milliseconds: int, _timeout: float | None = None) -> WaitResult:
        "Wait with cooperative cancellation."
        _bridge_require_sync()
        result = self.call("wait", {"milliseconds": milliseconds}, timeout=_timeout)
        return _bridge_decode(_bridge_type_WaitResult, result)

class TextKit(AsyncClient):
    def __init__(self, command=None, *, _runtime: RuntimeOptions | None = None):
        _bridge_options = _runtime or RuntimeOptions()
        command = command if command is not None else _bridge_options.command
        command = command if command is not None else _bridge_resolve_binary(__file__, "textkit")
        super().__init__(command, timeout=_bridge_options.timeout, max_pending=_bridge_options.max_pending,
                         startup_timeout=_bridge_options.startup_timeout, expected_schema="29b9c0dde82e391eaaf292e53d79f08996d07dea980b925695274369cf724472")

    def __enter__(self):
        raise TypeError("use async with TextKit(...), or with SyncTextKit(...)")

    async def analyze(self, *, text: str, _timeout: float | None = None) -> Analysis:
        "Count words and Unicode code points; cache results in Go."
        result = await self.acall("analyze", {"text": text}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Analysis, result)

    async def health(self, *, _timeout: float | None = None) -> Health:
        "Inspect the daemon for the integration example."
        result = await self.acall("health", {}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Health, result)

    async def wait(self, *, milliseconds: int, _timeout: float | None = None) -> WaitResult:
        "Wait with cooperative cancellation."
        result = await self.acall("wait", {"milliseconds": milliseconds}, timeout=_timeout)
        return _bridge_decode(_bridge_type_WaitResult, result)

_bridge_defaults = _bridge_Defaults(SyncTextKit)

async def analyze(*, text: str, _timeout: float | None = None) -> Analysis:
    "Count words and Unicode code points; cache results in Go."
    result = await _bridge_defaults.client().acall("analyze", {"text": text}, timeout=_timeout)
    return _bridge_decode(_bridge_type_Analysis, result)

def analyze_sync(*, text: str, _timeout: float | None = None) -> Analysis:
    "Count words and Unicode code points; cache results in Go."
    _bridge_require_sync()
    result = _bridge_defaults.client().call("analyze", {"text": text}, timeout=_timeout)
    return _bridge_decode(_bridge_type_Analysis, result)

async def health(*, _timeout: float | None = None) -> Health:
    "Inspect the daemon for the integration example."
    result = await _bridge_defaults.client().acall("health", {}, timeout=_timeout)
    return _bridge_decode(_bridge_type_Health, result)

def health_sync(*, _timeout: float | None = None) -> Health:
    "Inspect the daemon for the integration example."
    _bridge_require_sync()
    result = _bridge_defaults.client().call("health", {}, timeout=_timeout)
    return _bridge_decode(_bridge_type_Health, result)

async def wait(*, milliseconds: int, _timeout: float | None = None) -> WaitResult:
    "Wait with cooperative cancellation."
    result = await _bridge_defaults.client().acall("wait", {"milliseconds": milliseconds}, timeout=_timeout)
    return _bridge_decode(_bridge_type_WaitResult, result)

def wait_sync(*, milliseconds: int, _timeout: float | None = None) -> WaitResult:
    "Wait with cooperative cancellation."
    _bridge_require_sync()
    result = _bridge_defaults.client().call("wait", {"milliseconds": milliseconds}, timeout=_timeout)
    return _bridge_decode(_bridge_type_WaitResult, result)

def configure(command=None, *, _runtime: RuntimeOptions | None = None) -> None:
    _bridge_kwargs = {"command": command, "_runtime": _runtime}
    _bridge_defaults.configure(**_bridge_kwargs)

def session(command=None, *, _runtime: RuntimeOptions | None = None) -> _bridge_AsyncContextManager[TextKit]:
    _bridge_kwargs = {"command": command, "_runtime": _runtime}
    return _bridge_defaults.scope_for(TextKit, _bridge_kwargs)

def session_sync(command=None, *, _runtime: RuntimeOptions | None = None) -> _bridge_ContextManager[SyncTextKit]:
    _bridge_kwargs = {"command": command, "_runtime": _runtime}
    _bridge_require_sync()
    return _bridge_defaults.scope_for(SyncTextKit, _bridge_kwargs, asynchronous=False)

async def shutdown() -> None:
    """Close/reset the module default; explicit sessions stay open."""
    await _bridge_defaults.aclose()

def shutdown_sync() -> None:
    """Close/reset the default from synchronous code."""
    _bridge_require_sync()
    _bridge_defaults.close()
