# Generated by gobridge; DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from gobridge import Client, AsyncClient, RuntimeOptions, DefaultControl, decode as _bridge_decode, resolve_binary as _bridge_resolve_binary

@dataclass(frozen=True, kw_only=True)
class GreetParams:
    name: str

@dataclass(frozen=True, kw_only=True)
class Options:
    prefix: str | None = None

@dataclass(frozen=True, kw_only=True)
class ResetParams:
    pass

@dataclass(frozen=True, kw_only=True)
class Stats:
    calls: int
    process_id: int

@dataclass(frozen=True, kw_only=True)
class StatsParams:
    pass

@dataclass(frozen=True, kw_only=True)
class WelcomeParams:
    name: str

_bridge_type_GreetParams = GreetParams
_bridge_type_Options = Options
_bridge_type_ResetParams = ResetParams
_bridge_type_Stats = Stats
_bridge_type_StatsParams = StatsParams
_bridge_type_WelcomeParams = WelcomeParams

class Greeter(Client):
    def __init__(self, command=None, *, prefix: str | None = None, _runtime: RuntimeOptions | None = None):
        _bridge_options = _runtime or RuntimeOptions()
        command = command if command is not None else _bridge_options.command
        command = command if command is not None else _bridge_resolve_binary(__file__, "annotated")
        super().__init__(command, timeout=_bridge_options.timeout, max_pending=_bridge_options.max_pending,
                         startup_timeout=_bridge_options.startup_timeout, expected_schema="c6058a2c0f513c328f57e373ed031ec40d724d76e021e56aeaf83f9cbeec98a8", init={"prefix": prefix})

    def greet(self, *, name: str, _timeout: float | None = None) -> str:
        "Greet returns a friendly greeting using an ordinary Go function."
        result = self.call("greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(str, result)

    def reset(self, *, _timeout: float | None = None) -> None:
        "Reset clears the instance's call counter and returns None in Python."
        result = self.call("reset", {}, timeout=_timeout)
        return _bridge_decode(None, result)

    def stats(self, *, _timeout: float | None = None) -> Stats:
        "Statistics reports calls owned by this instance."
        result = self.call("stats", {}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Stats, result)

    def welcome(self, *, name: str, _timeout: float | None = None) -> str:
        "Welcome greets someone with this client's configured prefix."
        result = self.call("welcome", {"name": name}, timeout=_timeout)
        return _bridge_decode(str, result)

class AsyncGreeter(AsyncClient):
    def __init__(self, command=None, *, prefix: str | None = None, _runtime: RuntimeOptions | None = None):
        _bridge_options = _runtime or RuntimeOptions()
        command = command if command is not None else _bridge_options.command
        command = command if command is not None else _bridge_resolve_binary(__file__, "annotated")
        super().__init__(command, timeout=_bridge_options.timeout, max_pending=_bridge_options.max_pending,
                         startup_timeout=_bridge_options.startup_timeout, expected_schema="c6058a2c0f513c328f57e373ed031ec40d724d76e021e56aeaf83f9cbeec98a8", init={"prefix": prefix})

    async def greet(self, *, name: str, _timeout: float | None = None) -> str:
        "Greet returns a friendly greeting using an ordinary Go function."
        result = await self.acall("greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(str, result)

    async def reset(self, *, _timeout: float | None = None) -> None:
        "Reset clears the instance's call counter and returns None in Python."
        result = await self.acall("reset", {}, timeout=_timeout)
        return _bridge_decode(None, result)

    async def stats(self, *, _timeout: float | None = None) -> Stats:
        "Statistics reports calls owned by this instance."
        result = await self.acall("stats", {}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Stats, result)

    async def welcome(self, *, name: str, _timeout: float | None = None) -> str:
        "Welcome greets someone with this client's configured prefix."
        result = await self.acall("welcome", {"name": name}, timeout=_timeout)
        return _bridge_decode(str, result)

control = _bridge_control = DefaultControl(Greeter)

def greet(*, name: str, _timeout: float | None = None) -> str:
    "Greet returns a friendly greeting using an ordinary Go function."
    result = _bridge_control.client().call("greet", {"name": name}, timeout=_timeout)
    return _bridge_decode(str, result)

def reset(*, _timeout: float | None = None) -> None:
    "Reset clears the instance's call counter and returns None in Python."
    result = _bridge_control.client().call("reset", {}, timeout=_timeout)
    return _bridge_decode(None, result)

def stats(*, _timeout: float | None = None) -> Stats:
    "Statistics reports calls owned by this instance."
    result = _bridge_control.client().call("stats", {}, timeout=_timeout)
    return _bridge_decode(_bridge_type_Stats, result)

def welcome(*, name: str, _timeout: float | None = None) -> str:
    "Welcome greets someone with this client's configured prefix."
    result = _bridge_control.client().call("welcome", {"name": name}, timeout=_timeout)
    return _bridge_decode(str, result)

class _AsyncFunctions:
    async def greet(self, *, name: str, _timeout: float | None = None) -> str:
        "Greet returns a friendly greeting using an ordinary Go function."
        result = await _bridge_control.client().acall("greet", {"name": name}, timeout=_timeout)
        return _bridge_decode(str, result)

    async def reset(self, *, _timeout: float | None = None) -> None:
        "Reset clears the instance's call counter and returns None in Python."
        result = await _bridge_control.client().acall("reset", {}, timeout=_timeout)
        return _bridge_decode(None, result)

    async def stats(self, *, _timeout: float | None = None) -> Stats:
        "Statistics reports calls owned by this instance."
        result = await _bridge_control.client().acall("stats", {}, timeout=_timeout)
        return _bridge_decode(_bridge_type_Stats, result)

    async def welcome(self, *, name: str, _timeout: float | None = None) -> str:
        "Welcome greets someone with this client's configured prefix."
        result = await _bridge_control.client().acall("welcome", {"name": name}, timeout=_timeout)
        return _bridge_decode(str, result)

aio = _AsyncFunctions()
