// Code generated by gobridge generate; DO NOT EDIT.

package main

import _gobridge "github.com/sambhav/gobridge"

// NewGobridge registers annotated operations without running their constructors.
func NewGobridge() (*_gobridge.Registry, error) {
	_registry := _gobridge.New()
	_object, _err := _gobridge.NewObject(_registry, NewGreeter)
	if _err != nil {
		return nil, _err
	}
	if _err := _gobridge.Bind(_registry, "greet", Greet, "name"); _err != nil {
		return nil, _err
	}
	if _err := _registry.Describe("greet", "Greet returns a friendly greeting using an ordinary Go function."); _err != nil {
		return nil, _err
	}
	if _err := _object.Bind("reset", (*Greeter).Reset); _err != nil {
		return nil, _err
	}
	if _err := _registry.Describe("reset", "Reset clears the instance's call counter and returns None in Python."); _err != nil {
		return nil, _err
	}
	if _err := _object.Bind("stats", (*Greeter).Statistics); _err != nil {
		return nil, _err
	}
	if _err := _registry.Describe("stats", "Statistics reports calls owned by this instance."); _err != nil {
		return nil, _err
	}
	if _err := _object.Bind("welcome", (*Greeter).Welcome, "name"); _err != nil {
		return nil, _err
	}
	if _err := _registry.Describe("welcome", "Welcome greets someone with this client's configured prefix."); _err != nil {
		return nil, _err
	}
	return _registry, nil
}
