// Package sourcegen generates bridge registration from explicitly annotated Go declarations.
package sourcegen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/build"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

const marker = "// Code generated by gobridge generate; DO NOT EDIT."

type operation struct {
	name, function, receiver, description string
	params                                []string
	position                              token.Position
}

type declaration struct {
	fn      *ast.FuncDecl
	context string
}

// Generate scans one package using the host Go build constraints and writes an
// adapter in that package. It never loads or executes project code. output is a
// Go filename relative to dir; existing handwritten files are never overwritten.
func Generate(dir, output string) error {
	return generate(dir, output, false)
}

// Check reports stale or missing generated output without changing any files.
func Check(dir, output string) error {
	return generate(dir, output, true)
}

func generate(dir, output string, check bool) error {
	if filepath.Base(output) != output || !strings.HasSuffix(output, ".go") || strings.HasSuffix(output, "_test.go") || strings.HasPrefix(output, ".") || strings.HasPrefix(output, "_") {
		return fmt.Errorf("output must be a non-test Go filename within --dir")
	}
	path := filepath.Join(dir, output)
	previous, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	if err == nil && !bytes.HasPrefix(previous, []byte(marker+"\n")) {
		return fmt.Errorf("refusing to overwrite handwritten file %s; choose another --output", path)
	}
	if info, err := os.Lstat(path); err == nil && info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("refusing to overwrite symbolic link %s", path)
	}
	data, err := render(dir, output, build.Default)
	if err != nil {
		return err
	}
	if bytes.Equal(previous, data) {
		return nil
	}
	if check {
		return fmt.Errorf("generated adapter %s is missing or stale; run gobridge generate --dir %s --output %s", path, dir, output)
	}
	return os.WriteFile(path, data, 0o644)
}

func render(dir, output string, buildContext build.Context) ([]byte, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	var packageName string
	var declarations []declaration
	languageNames := map[string]map[string]map[string]string{}
	for _, lang := range []string{"python", "ts"} {
		languageNames[lang] = map[string]map[string]string{"types": {}, "operations": {}, "class": {}, "fields": {}}
	}
	names := make(map[string]bool)
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || name == output || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		match, err := buildContext.MatchFile(dir, name)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		if !match {
			continue
		}
		// We inspect declarations and import aliases, never ast.Ident.Obj/Scope.
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments|parser.SkipObjectResolution)
		if err != nil {
			return nil, err
		}
		if packageName != "" && packageName != file.Name.Name {
			return nil, fmt.Errorf("%s: package %s does not match %s", name, file.Name.Name, packageName)
		}
		packageName = file.Name.Name
		contextAlias := ""
		for _, imp := range file.Imports {
			importPath, _ := strconv.Unquote(imp.Path.Value)
			if importPath == "context" {
				contextAlias = "context"
				if imp.Name != nil {
					contextAlias = imp.Name.Name
				}
			}
		}
		for _, decl := range file.Decls {
			switch d := decl.(type) {
			case *ast.FuncDecl:
				if d.Recv == nil {
					names[d.Name.Name] = true
				}
				declarations = append(declarations, declaration{d, contextAlias})
			case *ast.GenDecl:
				for _, spec := range d.Specs {
					switch s := spec.(type) {
					case *ast.TypeSpec:
						names[s.Name.Name] = true
						doc := s.Doc
						if doc == nil {
							doc = d.Doc
						}
						renames, err := languageAnnotations(doc)
						if err != nil {
							return nil, fmt.Errorf("%s: %w", fset.Position(s.Pos()), err)
						}
						for lang, name := range renames {
							languageNames[lang]["types"][s.Name.Name] = name
						}
					case *ast.ValueSpec:
						for _, n := range s.Names {
							names[n.Name] = true
						}
					}
				}
			}
		}
	}
	if packageName == "" {
		return nil, fmt.Errorf("no Go source files match the current build configuration in %s", dir)
	}
	if names["NewGobridge"] {
		return nil, fmt.Errorf("NewGobridge is already declared; rename it or use the existing generated file as --output")
	}
	var operations []operation
	var constructor, receiver string
	var functional bool
	var optionFactories []operation
	seen := make(map[string]token.Position)
	for _, decl := range declarations {
		fn := decl.fn
		annotation, exposed, description, err := annotations(fn.Doc)
		position := fset.Position(fn.Pos())
		fail := func(err error) ([]byte, error) { return nil, fmt.Errorf("%s: %s: %w", position, fn.Name.Name, err) }
		if err != nil {
			return fail(err)
		}
		if annotation == "" {
			continue
		}
		if fn.Type.TypeParams != nil && len(fn.Type.TypeParams.List) != 0 {
			return fail(fmt.Errorf("generic declarations need a concrete wrapper"))
		}
		renames, renameErr := languageAnnotations(fn.Doc)
		if renameErr != nil {
			return fail(renameErr)
		}
		if annotation == "option" {
			if fn.Recv != nil {
				return fail(fmt.Errorf("option factory must be a function"))
			}
			if exposed == "" {
				exposed = snakeCase(strings.TrimPrefix(fn.Name.Name, "With"))
			}
			if !wireName.MatchString(exposed) {
				return fail(fmt.Errorf("invalid option name %q", exposed))
			}
			var params []string
			if len(resultTypes(fn.Type.Params)) > 1 {
				params, err = parameters(fn.Type.Params, "")
				if err != nil {
					return fail(err)
				}
			}
			optionFactories = append(optionFactories, operation{name: exposed, function: fn.Name.Name, position: position, params: params})
			for lang, name := range renames {
				languageNames[lang]["fields"][exposed] = name
			}
			continue
		}
		isFunctional := false
		if annotation == "constructor" && fn.Type.Params != nil && len(fn.Type.Params.List) > 0 {
			_, isFunctional = fn.Type.Params.List[len(fn.Type.Params.List)-1].Type.(*ast.Ellipsis)
		}
		var params []string
		if !isFunctional {
			params, err = parameters(fn.Type.Params, decl.context)
		}
		if err != nil {
			return fail(err)
		}
		if annotation == "constructor" {
			if fn.Recv != nil {
				return fail(fmt.Errorf("constructor must be a function, not a method"))
			}
			if constructor != "" {
				return fail(fmt.Errorf("multiple constructors: %s and %s; one object per registry is supported", constructor, fn.Name.Name))
			}
			if !isFunctional && len(params) != 1 {
				return fail(fmt.Errorf("constructor needs one named options parameter and optional leading context.Context"))
			}
			results := resultTypes(fn.Type.Results)
			if len(results) < 1 || len(results) > 2 || (len(results) == 2 && !isIdent(results[1], "error")) {
				return fail(fmt.Errorf("constructor must return *T or (*T, error)"))
			}
			pointer, ok := results[0].(*ast.StarExpr)
			if !ok {
				return fail(fmt.Errorf("constructor must return a pointer to a named local type"))
			}
			name, ok := pointer.X.(*ast.Ident)
			if !ok {
				return fail(fmt.Errorf("constructor must return a pointer to a named local type; generic receivers need a concrete wrapper"))
			}
			constructor, receiver = fn.Name.Name, name.Name
			functional = isFunctional
			for lang, public := range renames {
				languageNames[lang]["class"]["class"] = public
			}
			continue
		}
		if exposed == "" {
			exposed = snakeCase(fn.Name.Name)
		}
		if !wireName.MatchString(exposed) {
			return fail(fmt.Errorf("invalid operation name %q; use //gobridge:export lower_snake_case", exposed))
		}
		if prior, exists := seen[exposed]; exists {
			return fail(fmt.Errorf("operation name %q collides with declaration at %s", exposed, prior))
		}
		seen[exposed] = position
		for lang, name := range renames {
			languageNames[lang]["operations"][exposed] = name
		}
		op := operation{name: exposed, function: fn.Name.Name, params: params, description: description, position: position}
		if fn.Recv != nil {
			expr := fn.Recv.List[0].Type
			if ptr, ok := expr.(*ast.StarExpr); ok {
				expr = ptr.X
			}
			recv, ok := expr.(*ast.Ident)
			if !ok {
				return fail(fmt.Errorf("generic or unnamed receivers need a concrete wrapper"))
			}
			op.receiver = recv.Name
		}
		operations = append(operations, op)
	}
	if len(optionFactories) > 0 && !functional {
		return nil, fmt.Errorf("//gobridge:option requires a variadic //gobridge:constructor")
	}
	for _, lang := range []string{"python", "ts"} {
		if public, ok := languageNames[lang]["types"][receiver]; ok {
			if languageNames[lang]["class"]["class"] == "" {
				languageNames[lang]["class"]["class"] = public
			}
			delete(languageNames[lang]["types"], receiver)
		}
		fields := languageNames[lang]["fields"]
		qualified := map[string]string{}
		for name, value := range fields {
			qualified[receiver+"Config."+name] = value
		}
		languageNames[lang]["fields"] = qualified
	}
	if len(operations) == 0 {
		return nil, fmt.Errorf("no //gobridge:export declarations found in %s", dir)
	}
	for _, op := range operations {
		if op.receiver != "" && op.receiver != receiver {
			return nil, fmt.Errorf("%s: method %s receiver %s has no matching //gobridge:constructor", op.position, op.function, op.receiver)
		}
	}
	sort.Slice(operations, func(i, j int) bool { return operations[i].name < operations[j].name })
	unique := func(name string) string {
		for names[name] {
			name += "_"
		}
		names[name] = true
		return name
	}
	bridge, registry, object, errName := unique("_gobridge"), unique("_registry"), unique("_object"), unique("_err")
	optionsName := unique("_options")
	usesObject := false
	for _, op := range operations {
		usesObject = usesObject || op.receiver != ""
	}
	if !usesObject {
		object = "_"
	}
	var out bytes.Buffer
	fmt.Fprintf(&out, "%s\n\npackage %s\n\nimport %s %q\n\n", marker, packageName, bridge, "github.com/sambhav/gobridge")
	fmt.Fprintf(&out, "// NewGobridge registers annotated operations without running their constructors.\nfunc NewGobridge(%s ...%s.Option) (*%s.Registry, error) {\n", optionsName, bridge, bridge)
	hasNames := false
	for _, language := range languageNames {
		for _, values := range language {
			hasNames = hasNames || len(values) > 0
		}
	}
	if !hasNames {
		fmt.Fprintf(&out, "%s := %s.New(%s...)\n", registry, bridge, optionsName)
	} else {
		fmt.Fprintf(&out, "%s := %s.New(append([]%s.Option{", registry, bridge, bridge)
		for _, lang := range []string{"python", "ts"} {
			method := "WithPython"
			if lang == "ts" {
				method = "WithTypeScript"
			}
			fmt.Fprintf(&out, "%s.%s(%s.Names{", bridge, method, bridge)
			if class := languageNames[lang]["class"]["class"]; class != "" {
				fmt.Fprintf(&out, "Class:%q,", class)
			}
			for _, kind := range []string{"types", "operations", "fields"} {
				values := languageNames[lang][kind]
				if len(values) == 0 {
					continue
				}
				field := strings.ToUpper(kind[:1]) + kind[1:]
				fmt.Fprintf(&out, "%s:map[string]string{", field)
				keys := make([]string, 0, len(values))
				for key := range values {
					keys = append(keys, key)
				}
				sort.Strings(keys)
				for _, key := range keys {
					fmt.Fprintf(&out, "%q:%q,", key, values[key])
				}
				fmt.Fprint(&out, "},")
			}
			fmt.Fprint(&out, "}),")
		}
		fmt.Fprintf(&out, "},%s...)...)\n", optionsName)
	}
	if constructor != "" {
		fmt.Fprintf(&out, "%s, %s := %s.NewObject(%s, %s", object, errName, bridge, registry, constructor)
		// Source order is stable: sorted files, then declaration order.
		for _, option := range optionFactories {
			fmt.Fprintf(&out, ", %s.ConstructorOption(%q, %s", bridge, option.name, option.function)
			if len(option.params) > 1 {
				for _, param := range option.params {
					fmt.Fprintf(&out, ", %q", param)
				}
			}
			fmt.Fprint(&out, ")")
		}
		fmt.Fprintf(&out, ")\nif %s != nil {return nil,%s}\n", errName, errName)

	}
	for _, op := range operations {
		call := fmt.Sprintf("%s.Bind(%s, %q, %s", bridge, registry, op.name, op.function)
		if op.receiver != "" {
			call = fmt.Sprintf("%s.Bind(%q, (*%s).%s", object, op.name, op.receiver, op.function)
		}
		for _, param := range op.params {
			call += ", " + strconv.Quote(param)
		}
		fmt.Fprintf(&out, "if %s := %s); %s != nil { return nil, %s }\n", errName, call, errName, errName)
		if op.description != "" {
			fmt.Fprintf(&out, "if %s := %s.Describe(%q, %q); %s != nil { return nil, %s }\n", errName, registry, op.name, op.description, errName, errName)
		}
	}
	fmt.Fprintf(&out, "return %s, nil\n}\n", registry)
	return format.Source(out.Bytes())
}

var wireName = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

func annotations(group *ast.CommentGroup) (kind, name, description string, err error) {
	if group == nil {
		return
	}
	var lines []string
	for _, comment := range group.List {
		if !strings.HasPrefix(comment.Text, "//") {
			lines = append(lines, strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(comment.Text, "/*"), "*/")))
			continue
		}
		text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
		if !strings.HasPrefix(text, "gobridge:") {
			if !strings.HasPrefix(text, "go:") {
				lines = append(lines, text)
			}
			continue
		}
		if directive := strings.Fields(text)[0]; directive == "gobridge:python" || directive == "gobridge:ts" {
			continue
		}
		if kind != "" {
			err = fmt.Errorf("only one gobridge annotation is allowed per declaration")
			return
		}
		parts := strings.Fields(text)
		switch parts[0] {
		case "gobridge:option", "gobridge:export":
			if len(parts) > 2 {
				err = fmt.Errorf("use //gobridge:export [operation_name]")
				return
			}
			kind = strings.TrimPrefix(parts[0], "gobridge:")
			if len(parts) == 2 {
				name = parts[1]
			}
		case "gobridge:constructor":
			if len(parts) != 1 {
				err = fmt.Errorf("//gobridge:constructor takes no arguments")
				return
			}
			kind = "constructor"
		default:
			err = fmt.Errorf("unknown annotation %q", parts[0])
			return
		}
	}
	description = strings.TrimSpace(strings.Join(lines, "\n"))
	return
}

func parameters(fields *ast.FieldList, contextAlias string) ([]string, error) {
	var names []string
	seen := make(map[string]bool)
	if fields == nil {
		return names, nil
	}
	for i, field := range fields.List {
		if _, ok := field.Type.(*ast.Ellipsis); ok {
			return nil, fmt.Errorf("variadic parameters need an explicit slice wrapper")
		}
		if len(field.Names) == 0 {
			return nil, fmt.Errorf("unnamed parameters need names for Python keyword arguments")
		}
		for _, param := range field.Names {
			if param.Name == "_" {
				return nil, fmt.Errorf("blank parameters need meaningful names for source generation")
			}
		}
		if isContext(field.Type, contextAlias) {
			if i != 0 || len(field.Names) != 1 {
				return nil, fmt.Errorf("context.Context must be the first, single context parameter")
			}
			continue
		}
		for _, param := range field.Names {
			name := snakeCase(param.Name)
			if !wireName.MatchString(name) {
				return nil, fmt.Errorf("parameter %q cannot become a lower_snake_case wire name", param.Name)
			}
			if seen[name] {
				return nil, fmt.Errorf("parameter name %q collides after snake_case conversion", name)
			}
			seen[name] = true
			names = append(names, name)
		}
	}
	return names, nil
}

func isContext(expr ast.Expr, alias string) bool {
	if alias == "." {
		return isIdent(expr, "Context")
	}
	selector, ok := expr.(*ast.SelectorExpr)
	return ok && alias != "" && isIdent(selector.X, alias) && selector.Sel.Name == "Context"
}

func isIdent(expr ast.Expr, name string) bool {
	id, ok := expr.(*ast.Ident)
	return ok && id.Name == name
}

func resultTypes(fields *ast.FieldList) []ast.Expr {
	var types []ast.Expr
	if fields != nil {
		for _, field := range fields.List {
			count := len(field.Names)
			if count == 0 {
				count = 1
			}
			for i := 0; i < count; i++ {
				types = append(types, field.Type)
			}
		}
	}
	return types
}

func snakeCase(name string) string {
	runes := []rune(name)
	var out strings.Builder
	for i, r := range runes {
		if unicode.IsUpper(r) && i > 0 && runes[i-1] != '_' && (unicode.IsLower(runes[i-1]) || unicode.IsDigit(runes[i-1]) || (i+1 < len(runes) && unicode.IsLower(runes[i+1]))) {
			out.WriteByte('_')
		}
		out.WriteRune(unicode.ToLower(r))
	}
	return out.String()
}

// Language names are additional metadata, not export declarations.
func languageAnnotations(group *ast.CommentGroup) (map[string]string, error) {
	result := map[string]string{}
	if group == nil {
		return result, nil
	}
	for _, comment := range group.List {
		text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
		parts := strings.Fields(text)
		if len(parts) == 0 || (parts[0] != "gobridge:python" && parts[0] != "gobridge:ts") {
			continue
		}
		lang := strings.TrimPrefix(parts[0], "gobridge:")
		if len(parts) != 2 || result[lang] != "" {
			return nil, fmt.Errorf("use one //gobridge:%s name per declaration", lang)
		}
		result[lang] = parts[1]
	}
	return result, nil
}
